#lang pollen

◊head{
  ◊heading{Jacob Chvatal}
  ◊title{Computational Designer}
  ◊link{https://github.com/jakeisnt}
  ◊link{https://linkedin.com/in/jacob-chvatal}
  ◊summary{
    Formally trained engineer and self-taught product designer. I am passionate about the intersection of technology and the creative arts, in all its forms.
    Born, raised, and currently residing in the San Francisco Bay Area. Willing to relocate.
  }
}

◊body{
  ◊section{
    Work
    ◊experience{
      Uber
      Design Engineer
      ◊date{Feb. 2018 to Present}
      ◊expbody{
        ◊expbullet{Designed and built a suite of tools to help a team of 300+ designers do their best work. Involved in all stages of the product development process, from concept to mock to production code.}
        ◊expbullet{Contributor to Base, the Uber design system, powering experiences seen by millions worldwide.}
      }
    }
    ◊experience{
      Uber
      Software Engineering Intern
      ◊date{May 2017 - August 2017}
      ◊expbody{
        Growth and internal tools. Helped create improvements to the Uber driver signup flow, increasing UberMOTO registrations in Jakarta, Indonesia by 3%.
      }
    }
    ◊experience{
      Chartbeat
      Software Engineering Intern
      ◊date{June 2016 - Dec. 2016}
      ◊expbody{
        ◊expbullet{Front-end engineer at a 75 person startup.}
        ◊expbullet{Created a "trending topic" discovery tool, helping attract and retain clients (e.g. New York Times, the Atlantic, CNN). Contributed to core product redesign using React and Angular.}
      }
    }
  }
  ◊section{
    Education
    ◊experience{
      UC Berkeley
      BA, Computer Science
      2014-2017
      3.3 GPA
      ◊expbody{
        HCI emphasis. Extracirricular highlights include:
        ◊expbullet{Teaching front-end web development at Cal Hacks, the worlds largest collegiate hackathon}
        ◊expbullet{Leading design for Hackers@Berkeley, the worlds largest STEM organization. Marketed and promoted weekly events with as many as 1,000 attendees.}
        ◊expbullet{Creating a zine with lyrics generated by a recurrent neurla network}
        ◊expbullet{Creating a protest communication network post-2016 election, sending alerts to 500+ students daily}
        ◊expbullet{Writing a viral investigative article about "white student unions", receiving worldwide press coverage (NYT, CBC ancouver, Washington Post, etc.)}
        ◊expbullet{Prototyping a text input system for the Microsoft Hololens using Framer and Unity}
      }
    }
  }
  ◊section{
    Skills
    ◊experience{
      Design Tools
      ◊expbody{
        ◊explist{
          Figma
          Sketch
          Adobe Creative Suite
          Framer
        }
      }
    }
    ◊experience{
      Programming Languages + Frameworks
      ◊expbody{
        6+ years of experience in web development (React, Node, Angular). Familiar with mobile (Android + iOS) environments as well as prototyping in Unity.
      }
    }
  }
}

