#lang pollen

There are three layers here
- A format to encode a CV
- A maintainable formatting language that encodes the formatting of the CV
- The translation of this formatting language to viewable documents

1. Pattern match and mimic one resume
2. Abstract to ensure the formatting works for a second resume - the resume formatting language must be expressive enough to express most resumes without diving into the gory details
3. Abstract out the resume contents and make it target the formatting language

The code for the link should automatically parse the name of the service and the username from the link provided

◊head{
  ◊heading{Jacob Chvatal}
  ◊title{Computational Designer}
  ◊link{https://github.com/jakeisnt}
  ◊link{https://linkedin.com/in/jacob-chvatal}

  ◊description{
    Formally trained engineer and self-taught product designer. I am passionate about the intersection of technology and the creative arts, in all its forms.
    Born, raised, and currently residing in the San Francisco Bay Area. Willing to relocate.
  }
}

◊body{
  ◊section{
    ◊sectitle{Work}
    ◊experience{
      ◊exphead{
        Uber
        Design Engineer
        ◊date{Feb. 2018 to Present}
      }
      ◊expbody{
        Designed and built a suite of tools to help a team of 300+ designers do heir best work. Involved in all stages of he product development process, from concept to mock to production code.
        Contributor to Base, the Uber design system, powering experiences seen by millions worldwide.
      }
    }
    ◊experience{
      ◊exphead{
        Software Engineering Intern
        ◊date{May 2017 - August 2017}
      }
      ◊expbody{
        Growth and internal tools. Helped create improvements to the Uber driver signup flow, increasing UberMOTO registrations in Jakarta, Indonesia by 3%.
      }
    }
    ◊experience{
      ◊exphead{
        Chartbeat
        Software Engineering Intern
        ◊date{June 2016 - Dec. 2016}
      }
      ◊expbody{
        Front-end engineer at a 75 person startup.
        Created a "trending topic" discovery tool, helping attract and retain clients (e.g. New York Times, the Atlantic, CNN). Contributed to core product redesign using React and Angular.
      }
    }
  }
  ◊section{
    ◊title{Education}
    ◊experience{
      ◊exphead{
        UC Berkeley
        BA, Computer Science
        2014-2017
        3.3 GPA
      }
      ◊expbody{
        HCI emphasis. Extracirricular highlights include:

        - Teaching front-end web development at Cal Hacks, the worlds largest collegiate hackathon
        - Leading design for Hackers@Berkeley, the worlds largest STEM organization. Marketed and promoted weekly events with as many as 1,000 attendees.
        - Creating a zine with lyrics generated by a recurrent neurla network
        - Creating a protest communication network post-2016 election, sending alerts to 500+ students daily
        - Writing a viral investigative article about "white student unions", receiving worldwide press coverage (NYT, CBC ancouver, Washington Post, etc.)
        - Prototyping a text input system for the Microsoft Hololens using Framer and Unity
      }
    }
  }
  ◊section{
    ◊title{Skills}
    ◊experience{
      ◊exphead{
        Design Tools
      }
      ◊expbody{
        Figma, Sketch, Adobe Creative Suite, Framer
      }
    }
    ◊experience{
      ◊exphead{
        Programming Languages + Frameworks
      }
      ◊expbody{
        6+ years of experience in web development (React, Node, Angular). Familiar with mobile (Android + iOS) environments as well as prototyping in Unity.
      }
    }
  }
}

